config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: airbyte
      host: postgresql-123768-0.cloudclusters.net
      pass: '1234567890'
      port: 14120
      schema: public
      threads: 8
      type: postgres
      user: root
  target: prod
